### ISSUE TITLE
Recursive definitions are not OK? In the README.md of ajv it said "References can be recursive""

### ISSUE THREAD

**Issue by gatsbyz** [ajv-validator/ajv#1122]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
ajv@6.10.2 

**Ajv options object**

```javascript
{ allErrors: true, schemaId: 'auto', logger: false, useDefaults: true, passContext: true }

```

**JSON Schema**

http://json-schema.org/draft-04/schema#   or     http://json-schema.org/draft-07/schema#

**Sample data**

```yml

components:
  schemas:
    ISO8583Message:
      type: object
      additionalProperties: false
      required:
        - messageId
        - elements
      description: Message data that is being processed
      properties:
        messageId:
          type: string
          minLength: 1
        elements:
          type: array
          items:
            $ref: '#/components/schemas/DataElement'

    SubMessage:
      type: object
      additionalProperties: false
      required:
        - elementId
        - elements
      properties:
        elementId:
          type: string
          minLength: 1
        elements:
          type: array
          items:
            $ref: '#/components/schemas/DataElement'

    DataElement:
      oneOf:
        - $ref: '#/components/schemas/SimpleDataElement'
        - $ref: '#/components/schemas/SubMessage'

    SimpleDataElement:
      required:
        - elementId
        - value
      properties:
        elementId:
          type: string
          minLength: 1
        value:
          type: string
          minLength: 1
```
my code:
```
import Ajv from 'ajv';
/* tslint:disable-next-line:no-submodule-imports */
import * as draft4 from 'ajv/lib/refs/json-schema-draft-04.json';

const ajv = new Ajv({ allErrors: true, schemaId: 'id', logger: false, useDefaults: true });
ajv.addMetaSchema(draft4);


const compiledSchemaOfDocument = ajv.compile(schemaOfDocument);

export async function load(inputParam) {
  log('Loading document...');
  log('Resolving document references...');
  const input = await refParser.dereference(inputParam);
  log('Validating document against JSON-Schema...');
  const valid = compiledSchemaOfDocument(input);  // HERE
  if (!valid) {
    log('Document is not valid.');
    throw errorWrapper({ errors: compiledSchemaOfDocument.errors });
  }
  log('Finished validating document.');
  return input as VerifiedDocument;
}
```

**Validation result, data AFTER validation, error messages**

```
RangeError: Maximum call stack size exceeded
    at validate (eval at localCompile (/Users/jesselee/WebstormProjects/star/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:47577)
    at validate (eval at localCompile (/Users/jesselee/WebstormProjects/star/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:33226)
    at validate (eval at localCompile (/Users/jesselee/WebstormProjects/star/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:29910)
    at validate (eval at localCompile (/Users/jesselee/WebstormProjects/star/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:20250)
    at validate (eval at localCompile (/Users/jesselee/WebstormProjects/star/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:26862)
    at validate (eval at localCompile (/Users/jesselee/WebstormProjects/star/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:29910)
    at validate (eval at localCompile (/Users/jesselee/WebstormProjects/star/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:20250)
    at validate (eval at localCompile (/Users/jesselee/WebstormProjects/star/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:26862)
    at validate (eval at localCompile (/Users/jesselee/WebstormProjects/star/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:29910)
    at validate (eval at localCompile (/Users/jesselee/WebstormProjects/star/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:20250)


```

**What results did you expect?**
compilation

**Are you going to resolve the issue?**
if you want?

**Comment by epoberezkin** [comment]
The recursion is indeed supported (see the test for recursive schemas), but a very simple self-referencing schema `{$ref: '#'}` leading to endless recursion would exceed the stack.

To investigate the problem you need to keep reducing the size of the schema to the point when removing any part stops the issue from happening. Once you find the root cause (or the minimal schema with the problem) please update the issue - it will then be possible to determine whether it is a bug or the issue with the schema - at this schema size it is quite difficult.

**Comment by gatsbyz** [comment]
This is the minimal schema. I want the `SubMessage` to have the `element: DataElement[]` where `DataElement` is either `SubMessage` or `SimpleDataElement`. When `- $ref: '#/components/schemas/SubMessage'` is removed, it works fine because there is no recursion.

swagger.yml (OPENAPI)
```
components:
  schemas:
    SubMessage:
      type: object
      additionalProperties: false
      required:
        - elements
        elements:
          type: array
          items:
            $ref: '#/components/schemas/DataElement'

    DataElement:
      oneOf:
        - $ref: '#/components/schemas/SimpleDataElement'
        - $ref: '#/components/schemas/SubMessage'

    SimpleDataElement:
      required:
        - elementId
      properties:
        elementId:
          type: string
          minLength: 1
```

**Comment by epoberezkin** [comment]
It does compile - you do have missing "properties" keyword though.

https://runkit.com/esp/5dceeef4f870210013c38d29

Please submit the code that reproduces the issue to runkit.com

**Comment by gatsbyz** [comment]
@epoberezkin 

My full swagger.yml file looks like this
```

openapi: 3.0.0
info:
  title: STAR
  description: |
    #### Notes

  version: 1.0.0

servers:
  - url: /star/v1

x-firehose-logged: false

paths:

  /ping:
    get:
      summary: >-
        Tests the availability of the service and returns the current server
        time.
      responses:
        200:
          description: ping successful
          content:
            application/json:
              schema:
                type: object
                required:
                  - serverTime
                properties:
                  serverTime:
                    type: string
                    format: date-time
                    description: Current time on the server


components:
  schemas:
    SubMessage:
      type: object
      additionalProperties: false
      required:
        - elements
      properties:
        elements:
          type: array
          items:
            $ref: '#/components/schemas/DataElement'

    DataElement:
      oneOf:
        - $ref: '#/components/schemas/SimpleDataElement'
        - $ref: '#/components/schemas/SubMessage'

    SimpleDataElement:
      required:
        - elementId
      properties:
        elementId:
          type: string
          minLength: 1

```

**Comment by epoberezkin** [comment]
As I wrote, for me to be able to investigate the issue please submit the full working sample that reproduces the error to runkit.com - see the link in my previous comment.

**Comment by gatsbyz** [comment]
@epoberezkin Hi. Sorry that took a while! I guess I was confused about what I was asking myself.

https://runkit.com/gatsbyz/5ddec1f728087d001b7061c5

The reason I am having trouble is because I'm putting a circular structure (from `.dereference`) into the `Ajv.compile`. Is there a way for Ajv to understand this? Thanks.

**Comment by epoberezkin** [comment]
Ajv does not support circular data structures in schemas. You should not deference $refs, they have to stay in schema and be passed to Ajv.
