### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by Relequestual** [ajv-validator/ajv#1130]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.10.2

**Ajv options object**
NA.
This issue is with tests.

I clone the repo.
I install node 12.13.1 (LTS)
I run `npm install` and `git submodule update --init`.
I run `npm test`.

I get the following error logs...

<details><summary>.npm/_logs/2019-12-03T13_11_47_708Z-debug.log</summary>

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/bh7/.nvm/versions/node/v12.13.1/bin/node',
1 verbose cli   '/Users/bh7/.nvm/versions/node/v12.13.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test-all'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose run-script [ 'pretest-all', 'test-all', 'posttest-all' ]
5 info lifecycle ajv@6.10.2~pretest-all: ajv@6.10.2
6 info lifecycle ajv@6.10.2~test-all: ajv@6.10.2
7 verbose lifecycle ajv@6.10.2~test-all: unsafe-perm in lifecycle true
8 verbose lifecycle ajv@6.10.2~test-all: PATH: [all the path stuff]
9 verbose lifecycle ajv@6.10.2~test-all: CWD: /Users/bh7/projects/JSON Schema/ajv
10 silly lifecycle ajv@6.10.2~test-all: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'npm run test-ts && npm run test-cov && if-node-version 10 npm run test-browser'
10 silly lifecycle ]
11 silly lifecycle ajv@6.10.2~test-all: Returned: code: 1  signal: null
12 info lifecycle ajv@6.10.2~test-all: Failed to exec test-all script
13 verbose stack Error: ajv@6.10.2 test-all: `npm run test-ts && npm run test-cov && if-node-version 10 npm run test-browser`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/bh7/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/Users/bh7/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid ajv@6.10.2
15 verbose cwd /Users/bh7/projects/JSON Schema/ajv
16 verbose Darwin 17.7.0
17 verbose argv "/Users/bh7/.nvm/versions/node/v12.13.1/bin/node" "/Users/bh7/.nvm/versions/node/v12.13.1/bin/npm" "run" "test-all"
18 verbose node v12.13.1
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 1
22 error ajv@6.10.2 test-all: `npm run test-ts && npm run test-cov && if-node-version 10 npm run test-browser`
22 error Exit status 1
23 error Failed at the ajv@6.10.2 test-all script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
/Users/bh7/.npm/_logs/2019-12-03T13_11_47_708Z-debug.log (END)
```
</details>

<details><summary>.npm/_logs/2019-12-03T13_11_47_682Z-debug.log</summary>

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/bh7/.nvm/versions/node/v12.13.1/bin/node',
1 verbose cli   '/Users/bh7/.nvm/versions/node/v12.13.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test-ts'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose run-script [ 'pretest-ts', 'test-ts', 'posttest-ts' ]
5 info lifecycle ajv@6.10.2~pretest-ts: ajv@6.10.2
6 info lifecycle ajv@6.10.2~test-ts: ajv@6.10.2
7 verbose lifecycle ajv@6.10.2~test-ts: unsafe-perm in lifecycle true
8 verbose lifecycle ajv@6.10.2~test-ts: PATH: [all the path stuff]
9 verbose lifecycle ajv@6.10.2~test-ts: CWD: /Users/bh7/projects/JSON Schema/ajv
10 silly lifecycle ajv@6.10.2~test-ts: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'tsc --target ES5 --noImplicitAny --noEmit spec/typescript/index.ts'
10 silly lifecycle ]
11 silly lifecycle ajv@6.10.2~test-ts: Returned: code: 1  signal: null
12 info lifecycle ajv@6.10.2~test-ts: Failed to exec test-ts script
13 verbose stack Error: ajv@6.10.2 test-ts: `tsc --target ES5 --noImplicitAny --noEmit spec/typescript/index.ts`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/bh7/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/Users/bh7/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid ajv@6.10.2
15 verbose cwd /Users/bh7/projects/JSON Schema/ajv
16 verbose Darwin 17.7.0
17 verbose argv "/Users/bh7/.nvm/versions/node/v12.13.1/bin/node" "/Users/bh7/.nvm/versions/node/v12.13.1/bin/npm" "run" "test-ts"
18 verbose node v12.13.1
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 1
22 error ajv@6.10.2 test-ts: `tsc --target ES5 --noImplicitAny --noEmit spec/typescript/index.ts`
22 error Exit status 1
23 error Failed at the ajv@6.10.2 test-ts script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
</details>

I cursuary google suggested it could be a typescript issue.

I tried to re-run the tests having installed typescript 3. No joy.

(Please come find me on slack to discuss =] - Otherwise I'll likely find a reply weeks later...)

**Comment by epoberezkin** [comment]
@Relequestual not sure. works for me on clean install on mac, and works on travis (linux). Is it on windows?

**Comment by Relequestual** [comment]
Nope, not windows. Mac.
What version of nvm/node/npm are you using?

**Comment by Relequestual** [comment]
Sorry, I didn't give the specific failure...

```
> tsc --target ES5 --noImplicitAny --noEmit spec/typescript/index.ts

../../../node_modules/@types/unist/index.d.ts:31:20 - error TS2304: Cannot find name 'unknown'.

31     [key: string]: unknown;
                      ~~~~~~~
```
....

**Comment by epoberezkin** [comment]
Not sure what unist is... maybe you have old typescript?

**Comment by Relequestual** [comment]
Using version 3.7.2

**Comment by epoberezkin** [comment]
Weird. All works for me with the latest node/npm.

I just used `nvm install 12` to install node and npm - can you try that and also do clean install of Ajv to some empty folder to narrow down what happens? It does look like some sub-dependency version resolution conflict - I don’t think npm addressed that issue.

If it doesn’t help - can you try using yarn instead? 

Travis does clean install on every build in 4 different node versions without any issues btw - you may try comparing it’s npm install log and dependency tree with your install log and tree to see what differences are there.

**Comment by epoberezkin** [comment]
@Relequestual Hi Ben - I'd appreciate if you could check with v7-alpha branch. Closing the issue here.
