### ISSUE TITLE
Getting error related to uglify while building the application when I add ajv.addSchema in code

### ISSUE THREAD

**Issue by ankitdedhia007** [ajv-validator/ajv#1222]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.10.x

AJV version: 6.10.x;

UglifyJS version: uglifyjs-webpack-plugin = 1.3.x;

in tsconfig.json: "target": "es5",

in package.json: "react-scripts": "1.0.17

**Ajv options object**

```javascript
allErrors: true,
jsonPointers: true,
$data: true,
format: 'full',
addUsedSchema: false

```

**JSON Schema**

```

{}
I can say whatever schema I try to add, even an {} as well.
In general schema is quite big to post here, but it has,
{
"$id", "title", "description", "type", "properties", 
"oneOf", "anyRequired", "allOf" tags and allOf has if then else condition.
```

**Sample data**

```json
Did not reach to the part of validating data.

```

**Your code**

```javascript
export function addSchema(schema: Object) {
    if (!_.isNil(ajv.getSchema(schema['$id']))) {
        return;
    }
    return ajv.addSchema(schema);
}

Calling addSchema function in code results in build failure with below error.

```

**Validation result, data AFTER validation, error messages**

```
[22:59:06] 'webpack-prod' errored after 35 s
[22:59:06] Error: app.cb4d661d3807c23d1b05.js from UglifyJs
Unexpected token: name (e) [./node_modules/uri-js/dist/esnext/uri.js:42,0][app.cb4d661d3807c23d1b05.js:2172,8]
    at /local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/webpack/node_modules/uglifyjs-webpack-plugin/dist/index.js:233:34
    at Array.forEach (<anonymous>)
    at Compilation.<anonymous> (/local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/webpack/node_modules/uglifyjs-webpack-plugin/dist/index.js:54:20)
    at Compilation.applyPluginsAsyncSeries (/local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)
    at /local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/webpack/lib/Compilation.js:664:10
    at next (/local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/webpack/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/extract-text-webpack-plugin/dist/index.js:275:11)
    at Compilation.applyPluginsAsyncSeries (/local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)
    at sealPart2 (/local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/webpack/lib/Compilation.js:660:9)
    at next (/local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/webpack/node_modules/tapable/lib/Tapable.js:202:11)
    at /local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/extract-text-webpack-plugin/dist/index.js:244:13
    at /local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/async/dist/async.js:998:13)
    at /local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/async/dist/async.js:906:16
    at /local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/extract-text-webpack-plugin/dist/index.js:227:15
    at /local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/async/dist/async.js:998:13)
    at /local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/async/dist/async.js:906:16
    at /local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/extract-text-webpack-plugin/dist/index.js:216:21
    at /local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/webpack/lib/Compilation.js:528:29
    at Array.forEach (<anonymous>)
    at callback (/local/home/dedhiaa/workplace/AWSYachtUI/src/AWSYachtUI/node_modules/webpack/lib/Compilation.js:528:15)

```

**What results did you expect?**
Successful build without any uglify error.

**Are you going to resolve the issue?**
nope.

**Comment by epoberezkin** [comment]
That is not a bug, it seems to be compatibility or dependency/installation issue. I suggest re-installing everything starting from empty node_modules, and then, if the issue persists, try removing other packages (and the code that uses them) one by one until there is nothing but Ajv left. Please resubmit as "compatibility" or "installation" issue - whichever will seem more applicable.
