### ISSUE TITLE
Internal error when validating date-time in full mode

### ISSUE THREAD

**Issue by pallix** [ajv-validator/ajv#223]
There is an internal error when validating a `date-time` format with the `'format': 'full'` option.

```
> validate({agent_ip: "", timestamp: "2016-01-02"}, schema)
TypeError: Cannot read property 'match' of undefined
    at o (/home/miaou/projects/events/couchapp-tos/couch/_design/url/validation/lib/ajv.js:2:6022)
    at Object.i [as validate] (/home/miaou/projects/events/couchapp-tos/couch/_design/url/validation/lib/ajv.js:2:6162)
    at validate (eval at localCompile (/home/miaou/projects/events/couchapp-tos/couch/_design/url/validation/lib/ajv.js:2:12680), <anonymous>:1:1259)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
```

**Comment by epoberezkin** [comment]
can you post the full failing code please? Schema seems to be invalid, maybe nothing to do with format.

**Comment by epoberezkin** [comment]
See https://tonicdev.com/esp/577c211846395d1200bb9b52

The value that you have is not a valid "date-time", it is a valid "date" though.

Also, I am not sure what `validate` is, if it's ajv.validate (as it seems from the error), then the schema should be the first argument. See [Getting started](https://github.com/epoberezkin/ajv#getting-started)

**Comment by epoberezkin** [comment]
closing, please reopen if you have a failing code and above is not helpful. Thank you
