### ISSUE TITLE
strictTuples warning when using 2020-12 draft prefixItems with optional

### ISSUE THREAD

**Issue by KuSh** [ajv-validator/ajv#2241]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
I'm using latest Ajv version as of now (8.12.0)

**Ajv options object**

```javascript
const options = { allErrors: true };
```

**JSON Schema**

```json
{
  "$id": "https://www.example.com/schemas/test",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "A schema for unit testing",
  "type": "object",
  "properties": {
    "foo": {
      "type": "string",
      "minLength": 2
    },
    "bar": {
      "type": "number",
      "minimum": 0
    },
    "baz": {
      "type": "array",
      "items": { "type": "string" },
      "minItems": 2,
      "prefixItems": [{ "const": "test" }]
    }
  },
  "required": ["foo", "baz"]
}
```

**Sample data**

```json
{
  "foo": "foo",
  "bar": 1,
  "baz": ["test", "ok"]
}
```

**Your code**

```javascript
import Ajv from 'ajv/dist/2020';
const ajv = new Ajv();
const validate = ajv.compile(schema);
const valid = validate(data); // warn: strict mode: "prefixItems" is 2-tuple, but minItems or maxItems/items are not specified or different at path "#/properties/baz"
```

**Validation result, data AFTER validation, error messages**

```javascript
{
  errors: null,
  schema: {
    '$id': 'https://www.example.com/schemas/test',
    '$schema': 'https://json-schema.org/draft/2020-12/schema',
    description: 'A schema for unit testing',
    type: 'object',
    properties: { foo: [Object], bar: [Object], baz: [Object] },
    required: [ 'foo', 'baz' ]
  },
  schemaEnv: <ref *1> SchemaEnv {
    refs: {},
    dynamicAnchors: {},
    schema: {
      '$id': 'https://www.example.com/schemas/test',
      '$schema': 'https://json-schema.org/draft/2020-12/schema',
      description: 'A schema for unit testing',
      type: 'object',
      properties: [Object],
      required: [Array]
    },
    schemaId: '$id',
    root: [Circular *1],
    baseId: 'https://www.example.com/schemas/test',
    schemaPath: undefined,
    localRefs: {},
    meta: undefined,
    '$async': undefined,
    validateName: ValueScopeName {
      str: 'validate20',
      prefix: 'validate',
      value: [Object],
      scopePath: [_Code]
    },
    validate: [Circular *2]
  },
  evaluated: {
    props: { foo: true, bar: true, baz: true },
    items: undefined,
    dynamicProps: false,
    dynamicItems: false
  }
}
```

**What results did you expect?**
No warning. The spec has specifically [changed the way to declare tuples and arrays](https://json-schema.org/draft/2020-12/release-notes.html#changes-to-items-and-additionalitems) to avoid this sort of confusion and I'm not sure the warning is still needed

**Are you going to resolve the issue?**
You mean through an PR? I can certainly do that if that's wanted

**Comment by epoberezkin** [comment]
it's a possible enhancement to make strictTuples behave differently in draft2020-12. You still can define open tuples in 2020-12, and the idea of this option is to prevent you from using open tuples as they are better avoided in JSON. A stronger opinion that JTD enforces is that any tuples are better avoided in JSON as there is no cross-platform support for them, but it's another story.

**Comment by coderextreme** [comment]
I can't figure out an incantation for draft 2020-12 for a 4x4 matrix which doesn't throw an error in strict mode.  Thrown error is below, with ajv 8.12.0.   Suggestions are welcome.

            "@matrix": {
              "$comment": "SFMatrix4f inputOutput",
              "type": "array",
              "prefixItems": [
                {
                  "default": 1,
                  "type": "number"
                },
                {
                  "default": 0,
                  "type": "number"
                },
                {
                  "default": 0,
                  "type": "number"
                },
                {
                  "default": 0,
                  "type": "number"
                },
                {
                  "default": 0,
                  "type": "number"
                },
                {
                  "default": 1,
                  "type": "number"
                },
                {
                  "default": 0,
                  "type": "number"
                },
                {
                  "default": 0,
                  "type": "number"
                },
                {
                  "default": 0,
                  "type": "number"
                },
                {
                  "default": 0,
                  "type": "number"
                },
                {
                  "default": 1,
                  "type": "number"
                },
                {
                  "default": 0,
                  "type": "number"
                },
                {
                  "default": 0,
                  "type": "number"
                },
                {
                  "default": 0,
                  "type": "number"
                },
                {
                  "default": 0,
                  "type": "number"
                },
                {
                  "default": 1,
                  "type": "number"
                }
              ],
	      "items": { "type": "number" },
              "minItems": 16,
              "maxItems": 16
            },


Error thrown is:

Error: strict mode: "prefixItems" is 16-tuple, but minItems or maxItems/items are not specified or different at path "#/oneOf/1/properties/%40matrix"
    at checkStrictMode (C:\Users\john\x3dvalidate\node_modules\ajv\dist\compile\util.js:174:15)
    at checkStrictTuple (C:\Users\john\x3dvalidate\node_modules\ajv\dist\vocabularies\applicator\items.js:46:40)
    at validateTuple (C:\Users\john\x3dvalidate\node_modules\ajv\dist\vocabularies\applicator\items.js:24:5)
    at Object.code (C:\Users\john\x3dvalidate\node_modules\ajv\dist\vocabularies\applicator\prefixItems.js:9:46)
    at keywordCode (C:\Users\john\x3dvalidate\node_modules\ajv\dist\compile\validate\index.js:464:13)
    at C:\Users\john\x3dvalidate\node_modules\ajv\dist\compile\validate\index.js:222:17
    at CodeGen.code (C:\Users\john\x3dvalidate\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (C:\Users\john\x3dvalidate\node_modules\ajv\dist\compile\codegen\index.js:568:18)
    at iterateKeywords (C:\Users\john\x3dvalidate\node_modules\ajv\dist\compile\validate\index.js:219:9)
    at groupKeywords (C:\Users\john\x3dvalidate\node_modules\ajv\dist\compile\validate\index.js:200:13)


The JSON being evaluated doesn't even have @matrix property.

I would love to use strict mode, but it's fouling up my user's logs with nonsense. I am getting older, and my vision may be failing!

Thanks!

**Comment by sinclairzx81** [comment]
> it's a possible enhancement to make strictTuples behave differently in draft2020-12.

@epoberezkin It would be great to have the current strict warning reviewed. I am actually in the process of trying to upgrade to 2020-12, but these strict warnings are proving to be a bit awkward. The main reason for wanting 2020-12 is to be able to represent data structures such as the following.

```typescript
// typescript
type T = [string, number, ...boolean[]]

// typebox
const T = Type.Tuple([
   Type.String(),
   Type.Number(),
   Type.Rest(Type.Boolean())
])

// json schema
const T = {
  type: "array",    
  prefixItems: [    
    { type: "string" },
    { type: "number" }
  ],
  "minItems": 2,
  "items": { type: "boolean" }
}
```
Which unfortunately results in the warning
```
strict mode: "prefixItems" is 2-tuple, but minItems or maxItems/items are not specified or different at path "#"
```
There doesn't appear to be way to express the above data structure without warning, but is there a technical reason why this schematic needs to warn in strict?
