### ISSUE TITLE
ajv can handle circular $refs, but not circular memory references

### ISSUE THREAD

**Issue by jedwards1211** [ajv-validator/ajv#2260]
**What version of Ajv are you using? Does the issue happen if you use the latest version?** 8.12.0

**Ajv options object**

```javascript
{strict: false, logger: false}
```

**JSON Schema**

```js
const schema = {
  type: 'object',
  properties: {
    value: { type: 'number' },
    // left: { $ref: '#' },
    // right: { $ref: '#' },
  },
  required: ['value'],
};
schema.properties.left = schema;
schema.properties.right = schema;
```

I'm working with a schema in code that has already resolved `$refs` to JS references, so I'd like to be able to use such a schema with `ajv`.

**Sample data**

```json
{ "value": 1, "left": { "value": 5 } }
```

**Your code**

```javascript
import Ajv from 'ajv';

const schema = {
  type: 'object',
  properties: {
    value: { type: 'number' },
    // left: { $ref: '#' },
    // right: { $ref: '#' },
  },
  required: ['value'],
};
schema.properties.left = schema;
schema.properties.right = schema;

const ajv = new Ajv({ strict: false, logger: false });
ajv.validate(schema, { value: 1, left: { value: 5 } });
```

**Validation result, data AFTER validation, error messages**

```
RangeError: Maximum call stack size exceeded
    at _traverse (/Users/andy/github/stainless-3/node_modules/json-schema-traverse/index.js:67:19)
    at _traverse (/Users/andy/github/stainless-3/node_modules/json-schema-traverse/index.js:83:9)
    at _traverse (/Users/andy/github/stainless-3/node_modules/json-schema-traverse/index.js:80:13)
```

**What results did you expect?**

Validation can handle circular references just as well as `$ref`s

**Are you going to resolve the issue?**

**Comment by epoberezkin** [comment]
not a bug, it's as documented - circular refs are not supported.
