### ISSUE TITLE
Combination of anyOf and default results in "default is ignored for: data.status" at compile

### ISSUE THREAD

**Issue by vincentcr** [ajv-validator/ajv#2311]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

Reproducible 8.8.2 and 8.12.0

**Ajv options object**

```javascript
new Ajv({
  useDefaults: true,
  allErrors: true,
})
```

**JSON Schema**

```json
{
  "anyOf": [
    {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "foo"
          ]
        }
      },
      "required": [
        "type"
      ]
    },
    {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "bar"
          ]
        },
        "status": {
          "type": "integer",
          "default": 503
        }
      },
      "required": [
        "type"
      ]
    }
  ]
}
```

**Sample data**

(N/A: fails compilation) 

**Your code**

```javascript
import Ajv from 'ajv'

const schema = {
  anyOf: [
    {
      type: 'object',
      properties: {
        type: {
          type: 'string',
          enum: ['foo'],
        },
      },
      required: ['type'],
    },
    {
      type: 'object',
      properties: {
        type: {
          type: 'string',
          enum: ['bar'],
        },
        status: {
          type: 'integer',
          default: 503,
        },
      },
      required: ['type'],
    },
  ],
}
console.log(JSON.stringify(schema, null, 2))

new Ajv({
  useDefaults: true,
  allErrors: true,
}).compile(schema)

```

**Validation result, data AFTER validation, error messages**
Fails to compile, with:
```
Error: strict mode: default is ignored for: data.status
    at checkStrictMode (dev/node_modules/ajv/lib/compile/util.ts:211:28)
    at assignDefault (dev/node_modules/ajv/lib/compile/validate/defaults.ts:21:20)
    at assignDefaults (dev/node_modules/ajv/lib/compile/validate/defaults.ts:9:7)
    at iterateKeywords (dev/node_modules/ajv/lib/compile/validate/index.ts:261:34)
    at groupKeywords (dev/node_modules/ajv/lib/compile/validate/index.ts:241:7)
    at dev/node_modules/ajv/lib/compile/validate/index.ts:233:38
    at CodeGen.code (dev/node_modules/ajv/lib/compile/codegen/index.ts:525:33)
    at CodeGen.block (dev/node_modules/ajv/lib/compile/codegen/index.ts:680:20)
    at schemaKeywords (dev/node_modules/ajv/lib/compile/validate/index.ts:232:7)
    at typeAndKeywords (dev/node_modules/ajv/lib/compile/validate/index.ts:161:3)
```

**What results did you expect?**

Schema compiles, this is a valid JSON schema.

**Are you going to resolve the issue?**

I don't know...

**Comment by epoberezkin** [comment]
not a bug, see strict mode doc and the limitations on defaults - it's all as documented

**Comment by vincentcr** [comment]
I see. Sorry I missed this in the doc.
