### ISSUE TITLE
ajv not reading my schema

### ISSUE THREAD

**Issue by doebi** [ajv-validator/ajv#2335]
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

**Ajv options object**

```javascript

```

**JSON Schema**

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "project",
  "description": "A project",
  "type": "object",
  "properties": {
    "project_id": {
      "description": "the id of the project",
      "type": "string",
      "format": "uuid"
    }
  }
}

```

**Sample data**

```json
{
  "project_id": "foo"
}

```

**Your code**

```javascript
#!/usr/bin/env node
const Ajv = require("ajv");
const fs = require('fs');

const instanceFilename = process.argv[2];
const schemaFilename = process.argv[3];

const schema = JSON.parse(fs.readFileSync(schemaFilename, 'utf8'));
const instance = JSON.parse(fs.readFileSync(instanceFilename, 'utf8'));

const ajv = new Ajv()

const validate = ajv.compile(schema)
const valid = validate(instance)
if (!valid) console.log(validate.errors)

```

**Validation result, data AFTER validation, error messages**

```
                throw new Error(`no schema with key or ref "${schemaKeyRef}"`);
                ^

Error: no schema with key or ref "https://json-schema.org/draft/2020-12/schema"
    at Ajv.validate (/home/doebi/repos/DCS/engicloud-documentation/specs/node_modules/ajv/dist/core.js:147:23)
    at Ajv.validateSchema (/home/doebi/repos/DCS/engicloud-documentation/specs/node_modules/ajv/dist/core.js:260:28)
    at Ajv._addSchema (/home/doebi/repos/DCS/engicloud-documentation/specs/node_modules/ajv/dist/core.js:460:18)
    at Ajv.compile (/home/doebi/repos/DCS/engicloud-documentation/specs/node_modules/ajv/dist/core.js:158:26)
    at Object.<anonymous> (/home/doebi/repos/DCS/engicloud-documentation/specs/validate.js:13:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)


```

**What results did you expect?**

i want to write myself a validator to be able to develop my schema and validate it on the go against my testdata. With the current data I want it to fail because project_id is not of format uuid. The python validator i used previously didn provide this functionality, and ajv doesnt even seem to know of 2020-12

**Are you going to resolve the issue?**

**Comment by jeremyfiel** [comment]
for 2020-12 you need to use the 2020 import which has the 2020-12 metaschema 

```javascript
const Ajv = require('ajv/dist/2020');
const ajv = new Ajv({ strict: false });

let instance = // your json data instance, either inline or loaded from a file or url
const schema = // your json schema, either inline or loaded from a file or url


try {
    const validate = ajv.compile(schema)

    const valid = validate(instance)

    console.log(results = { valid: valid, error: validate.errors })
} catch ({ message }) {
    console.error(message)
}
```

**Comment by jason-curtis** [comment]
thanks @jeremyfiel, I was having this issue and your suggestion resolved it!

**Comment by richardhj** [comment]
I am using CLI - what can I do to fix this error?

**Comment by jeremyfiel** [comment]
I think cli has a flag .. something like. ` --2020-12 `

**Comment by DavidBiesack** [comment]
Use the CLI option `--spec=draft2020` as per https://github.com/ajv-validator/ajv-cli#readme

**Comment by kleinfreund** [comment]
The CLI option is `--spec=draft2020`
