### ISSUE TITLE
Allow it to work on edge (e.g. cloudflare workers)

### ISSUE THREAD

**Issue by ValeryG** [ajv-validator/ajv#2491]
There is already an issue for this , https://github.com/ajv-validator/ajv/issues/2318, but it is closed. Suggestion there is not working when ajv is XX-layers down like eg: [async-parser](https://github.com/asyncapi/parser-js) -> [@stoplight/spectral](https://github.com/stoplightio/spectral)->ajv and dynamic schema is validated, there is not visible to generate and pass validation function all the way down.

**The version of Ajv you are using**
latest

**The environment you have the problem with**
cloudflare worker

**Your code (please make it as small as possible to reproduce the issue)**
standard example from async-parser [Example](https://github.com/asyncapi/parser-js?tab=readme-ov-file#example-with-parsing)

Works in every browser and node env, except of cloudflare worker. 

**Results and error messages in your platform**
```
 Code generation from strings disallowed for this context

      at new Function (<anonymous>)
      at m.f
```

If there is no way to drop `new Function` usage in general, maybe it could be made conditional? let's say if `option.workerSafe` is passed as true, do something worker safe instead of new function?

**Comment by jasoniangreen** [comment]
I see, so the use of AJV within other projects preclude those projects from being used in cloudflare. I wonder if it would be possible for those projects to pre-build any schema based validations functions so that their code can be run on cloudflare? It won't always be possible but not out of the question depending on the usage.

I say this because given how AJV works I can't think of a way to avoid using `new Function`. Also worth noting, just in case it was a concern, that while `new Function` is considered unsafe and not allowed on cloudflare, the way that AJV uses it is very safe and has been verified by many experts. Anything passed to `new Function` has had to go through the typesafe codegen package which protects against any injection attacks etc.

Anyway, I am open to ideas but afaik we couldn't stop using `new Function`.

**Comment by adamdehaven** [comment]
> I wonder if it would be possible for those projects to pre-build any schema based validations functions so that their code can be run on cloudflare?

No, since the source files are fetched at runtime, there’s bo way to pre-build.

**Comment by jasoniangreen** [comment]
I see. Well I will leave this open. If anyone has any ideas on how to work around this or any proposals, we can discuss it.

**Comment by Justineo** [comment]
As Cloudflare doesn't allow `eval` or `new Function` for security reasons, it may someday support ShadowRealm API if it gets approved by TC39 (it's currently in [Stage 2.7](https://github.com/tc39/proposals?tab=readme-ov-file#stage-27) and [Bun already supported it](https://x.com/jarredsumner/status/1497351968112607234)). At that time ajv should be able to migrate to the new API to make it work on edge runtimes.

**Comment by jasoniangreen** [comment]
Thanks for the info @Justineo, I will keep an eye out for that.

**Comment by ama-coder** [comment]
is there anyway to workaround this and make Ajv run on edge just for now?

**Comment by cmsparks** [comment]
BTW there's a workaround for this: https://developers.cloudflare.com/workers/configuration/compatibility-flags/#enable-eval-during-startup

As long as you only compile during script startup, AJV is functional on Cloudflare Workers.

**Comment by regseb** [comment]
There's the same issue with the [`--disallow-code-generation-from-strings`](https://nodejs.org/api/cli.html#disallow-code-generation-from-strings) option in Node.js.

```
Error compiling schema, function code: const schema2 = scope.schema[2];const schema1 = scope.schema[1];return function validate1(data, {instancePath="", parentData, parentDataProperty, rootData=data}={}){let vErrors = null;let errors = 0;const _errs1 = errors;if(!(((typeof data == "number") && (!(data % 1) && !isNaN(data))) && (isFinite(data)))){validate1.errors = [{instancePath,schemaPath:"#/definitions/nonNegativeInteger/type",keyword:"type",params:{type: "integer"},message:"must be integer"}];return false;}if(errors === _errs1){if((typeof data == "number") && (isFinite(data))){if(data < 0 || isNaN(data)){validate1.errors = [{instancePath,schemaPath:"#/definitions/nonNegativeInteger/minimum",keyword:"minimum",params:{comparison: ">=", limit: 0},message:"must be >= 0"}];return false;}}}validate1.errors = vErrors;return errors === 0;}
metalint: Code generation from strings disallowed for this context
EvalError: Code generation from strings disallowed for this context
    at new Function (<anonymous>)
    at Ajv.compileSchema (/home/regseb/example/node_modules/@secretlint/config-loader/node_modules/ajv/dist/compile/index.js:89:30)
    at Ajv.inlineOrCompile (/home/regseb/example/node_modules/@secretlint/config-loader/node_modules/ajv/dist/compile/index.js:148:47)
    at Ajv.resolveRef (/home/regseb/example/node_modules/@secretlint/config-loader/node_modules/ajv/dist/compile/index.js:142:46)
    at Object.code (/home/regseb/example/node_modules/@secretlint/config-loader/node_modules/ajv/dist/vocabularies/core/ref.js:19:47)
    at keywordCode (/home/regseb/example/node_modules/@secretlint/config-loader/node_modules/ajv/dist/compile/validate/index.js:464:13)
    at /home/regseb/example/node_modules/@secretlint/config-loader/node_modules/ajv/dist/compile/validate/index.js:185:25
    at CodeGen.code (/home/regseb/example/node_modules/@secretlint/config-loader/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/home/regseb/example/node_modules/@secretlint/config-loader/node_modules/ajv/dist/compile/codegen/index.js:568:18)
    at schemaKeywords (/home/regseb/example/node_modules/@secretlint/config-loader/node_modules/ajv/dist/compile/validate/index.js:185:13)
```
