### ISSUE TITLE
Self referencing schema fails to compile

### ISSUE THREAD

**Issue by morsh** [ajv-validator/ajv#329]
ajv version: 4.8.2
ajv options: {allErrors: true, v5: true}

General description:
I have a problem compiling a circular, self referencing schema -

**JSON Schema**

``` json
var schema = {
  "type": "object",
  "id": "dialog",
  "properties": {
    "steps": { "$ref": "#/definitions/steps" },
  },
  "definitions": {
    "steps": {
      "id": "steps",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "steps": {
            "$ref": "#/definitions/steps"
          }
        }
      }
    }
  }
}
;
```

**Code**

``` javascript
var Ajv = require('ajv');
var ajv = Ajv({allErrors: true, v5: true});

var schema = {...};
var validate = ajv.compile(schema);

```

**Result**
I expect this schema to compile, but I see the following exception:

```
        throw $error;
        ^

Error: can't resolve reference #/definitions/steps from id steps
    at Object.generate_ref [as code] (c:\temp\ajv-test\node_modules\ajv\lib\dotjs\ref.js:62:22)
    at Object.generate_validate [as validate] (c:\temp\ajv-test\node_modules\ajv\lib\dotjs\validate.js:157:37)
    at Object.generate_properties [as code] (c:\temp\ajv-test\node_modules\ajv\lib\dotjs\properties.js:198:26)
    at Object.generate_validate [as validate] (c:\temp\ajv-test\node_modules\ajv\lib\dotjs\validate.js:230:37)
    at Object.generate_items [as code] (c:\temp\ajv-test\node_modules\ajv\lib\dotjs\items.js:122:20)
    at generate_validate (c:\temp\ajv-test\node_modules\ajv\lib\dotjs\validate.js:230:37)
    at Ajv.localCompile (c:\temp\ajv-test\node_modules\ajv\lib\compile\index.js:98:22)
    at Ajv.resolve (c:\temp\ajv-test\node_modules\ajv\lib\compile\resolve.js:53:19)
    at Object.resolveRef (c:\temp\ajv-test\node_modules\ajv\lib\compile\index.js:209:21)
    at Object.generate_ref [as code] (c:\temp\ajv-test\node_modules\ajv\lib\dotjs\ref.js:22:22)

```

**Comment by epoberezkin** [comment]
I understand the issue. The problem is {"id": "steps"}, it makes "#/definitions/steps" resolve to "stesp#/definitions/steps" i.e. some fragment of schema with id "steps" and although this "id" exists here, there are no "definitions" inside it. That's by the spec. See this schema:

```
{
  "type": "object",
  "id": "dialog",
  "properties": {
    "steps": { "$ref": "#/definitions/steps" },
  },
  "definitions": {
    "steps": {
      "id": "steps",
      "definitions": {
        "steps": {
          "description": "this is what internal $ref points to, but it does not exist in your schema"
        }
      },
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "steps": {
            "$ref": "#/definitions/steps"
          }
        }
      }
    }
  }
}
```

You just need to remove this id, it serves no purpose.

Maybe the intention was to have "id": "#steps" to be able to use it instead of "#/definitions/steps"? This would work.

I hope it makes sense.

**Comment by epoberezkin** [comment]
Actually the error message gives a subtle hint: "can't resolve reference #/definitions/steps from id steps". The key here was "from id steps" :)

**Comment by morsh** [comment]
@epoberezkin 
That did some of the work, changing to #steps does the trick, but backtracking closer to my original schema, I get an error on the following schema:

``` json
{
  "type": "object",
  "id": "dialog",
  "properties": {
    "steps": { "$ref": "#steps" },
  },
  "definitions": {
    "steps": {
      "id": "#steps",
      "type": "array",
      "items": {
        "type": "object",
        "oneOf": [
          {
            "id": "step",
            "type": "object",
            "properties": {
              "steps": {
                "$ref": "#steps"
              }
            }
          }
        ]
      }
    }
  }
}
```

The error:

```
        throw $error;
        ^

Error: can't resolve reference #steps from id step
    at Object.generate_ref [as code] (c:\temp\ajv-test\node_modules\ajv\lib\dotjs\ref.js:62:22)
    at Object.generate_validate [as validate] (c:\temp\ajv-test\node_modules\ajv\lib\dotjs\validate.js:157:37)
    at Object.generate_properties [as code] (c:\temp\ajv-test\node_modules\ajv\lib\dotjs\properties.js:198:26)
    at Object.generate_validate [as validate] (c:\temp\ajv-test\node_modules\ajv\lib\dotjs\validate.js:230:37)
    at Object.generate_oneOf [as code] (c:\temp\ajv-test\node_modules\ajv\lib\dotjs\oneOf.js:31:27)
    at Object.generate_validate [as validate] (c:\temp\ajv-test\node_modules\ajv\lib\dotjs\validate.js:230:37)
    at Object.generate_items [as code] (c:\temp\ajv-test\node_modules\ajv\lib\dotjs\items.js:122:20)
    at generate_validate (c:\temp\ajv-test\node_modules\ajv\lib\dotjs\validate.js:230:37)
    at Ajv.localCompile (c:\temp\ajv-test\node_modules\ajv\lib\compile\index.js:98:22)
    at Ajv.resolve (c:\temp\ajv-test\node_modules\ajv\lib\compile\resolve.js:53:19)

```

**Comment by epoberezkin** [comment]
The problem is `"id": "step"`. id attribute changes resolution scope (by spec), there is no `"#steps"` inside `"step"`, it's outside. Just remove it or replace with `"#step"`.

**Comment by morsh** [comment]
@epoberezkin changing to #step works, but I don't completely understand why

**Comment by epoberezkin** [comment]
@morsh because your $ref is a relative URI (hash fragment) and id attribute defines base URI for $ref. #step doesn't change base URI because it is also a fragment, step does because it's a different file name

**Comment by morsh** [comment]
@epoberezkin thank you!

**Comment by epoberezkin** [comment]
https://tools.ietf.org/html/rfc3986#section-5.1
