### ISSUE TITLE
Cannot find module '../dotjs/validate/

### ISSUE THREAD

**Issue by javidaslan** [ajv-validator/ajv#514]
Hi,

I am facing with the problem:

Error: Cannot find module '../dotjs/validate'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\user-pc\Desktop\pluralsight\nodejs\module2\node_modules\ajv\lib\compile\index.js:18:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Using latest AJV version. Don't know why does it occur. But note that I am installing modules manually because of some proxy problems but I have installed all dependencies as well. Could you help with this issue please?

**Comment by epoberezkin** [comment]
manually = without npm?

If you can't run `npm install`, you need to run `npm run build`

**Comment by tridium** [comment]
`npm run build` deletes the file lib/dotjs/index.js. As a workaround, I did `npm run build`, restored that file, then ran `npm run bundle`.

**Comment by BrianWendt** [comment]
`npm run build` didn't solve this for me. I'm new to node but if I figure it out I'll post here.

**Comment by BrianWendt** [comment]
`npm run build` encounters the same error.

npm 6.4.1 | node 10.15.3 | Windows 10
