### ISSUE TITLE
Local hash ref with remote hash ref that has inner hash ref (e.g. swagger api schema)

### ISSUE THREAD

**Issue by quilicicf** [ajv-validator/ajv#70]
### Reproduce
- run the following code: 
  
  ``` js
  'use strict'
  
  var fs = require('fs');
  
  var Ajv = require('ajv');
  var ajv = Ajv({jsonPointers: true, allErrors: true, verbose: true});
  
  function readFile (filePath) {
    return fs.readFileSync(filePath, 'utf8');
  }
  
  // Schema
  var schemaName = process.argv[2];
  var schema = JSON.parse(readFile(schemaName));
  
  var validate = ajv.compile(schema);
  ```
- with the schema file containing the schema at `https://raw.githubusercontent.com/swagger-api/swagger-spec/master/schemas/v2.0/schema.json`
### Error

```
node testJsonSchemaExternal.js /path/to/schema.json 
/home/cyp/node_modules/ajv/lib/dotjs/ref.js:81
        throw $error;
        ^

Error: can't resolve reference #/definitions/positiveInteger from id http://swagger.io/v2/schema.json#
    at Object.generate_ref [as code] (/home/cyp/node_modules/ajv/lib/dotjs/ref.js:78:22)
    at Object.generate_validate [as validate] (/home/cyp/node_modules/ajv/lib/dotjs/validate.js:43:35)
    at Object.generate_allOf [as code] (/home/cyp/node_modules/ajv/lib/dotjs/allOf.js:24:26)
    at generate_validate (/home/cyp/node_modules/ajv/lib/dotjs/validate.js:43:35)
    at localCompile (/home/cyp/node_modules/ajv/lib/compile/index.js:35:24)
    at Ajv.compile (/home/cyp/node_modules/ajv/lib/compile/index.js:27:10)
    at Ajv.localCompile (/home/cyp/node_modules/ajv/lib/compile/index.js:33:22)
    at Ajv.resolve (/home/cyp/node_modules/ajv/lib/compile/resolve.js:43:19)
    at Object.resolveRef (/home/cyp/node_modules/ajv/lib/compile/index.js:98:21)
    at Object.generate_ref [as code] (/home/cyp/node_modules/ajv/lib/dotjs/ref.js:33:22)
```

**Comment by epoberezkin** [comment]
Thanks, I'll have a look

**Comment by epoberezkin** [comment]
https://tonicdev.com/esp/563b71a6b859fd0c00ac4bf1

**Comment by quilicicf** [comment]
I like that tool (tonicdev) thanks for sharing :)

**Comment by epoberezkin** [comment]
Essentially this schema doesn't compile:

```
{ "$ref": "http://json-schema.org/draft-04/schema#/definitions/positiveIntegerDefault0" }
```

(hash ref inside hash ref in remore ref)

EDIT: It does compile...

**Comment by epoberezkin** [comment]
Yeah, I like Tonic too - very convenient to test stuff quickly, especially with ES7 support. I noticed the link in npm ("Test ajv in your browser") and asked them how I can add my own code to the link. They said it's not possible yet but they can "special-case" it. And they did :)

**Comment by epoberezkin** [comment]
Ok, I get it now.

This does not compile:

```
{
  "definitions": {
    "a": { "$ref": "http://json-schema.org/draft-04/schema#/definitions/positiveIntegerDefault0" }
  },
  "properties": {
    "b": { "$ref": "#/definitions/a" }
  }
}
```

And this does:

```
{
  "definitions": {
    "a": { "$ref": "http://json-schema.org/draft-04/schema#/definitions/positiveInteger" }
  },
  "properties": {
    "b": { "$ref": "#/definitions/a" }
  }
}
```

**Comment by epoberezkin** [comment]
Published 1.4.9 with the fix

**Comment by quilicicf** [comment]
Works like a charm thanks :)

**Comment by epoberezkin** [comment]
You're welcome :)
