### ISSUE TITLE
custom error message for format keyword

### ISSUE THREAD

**Issue by MeenalYengul** [ajv-validator/ajv#936]
AJV : 2.1

**JSON Schema**

```javascript
 var schema = {
         "required": ["OrderType","dateNeeded"],
            "type": "object",
            "properties": {
                "Order": {"type":"boolean"},
                "Mydate": {"type": "string","format": "date-time", errorMessage:{type:'Date must be a 
                  "mm-dd-yy" format........'}}
},
  errorMessage: { 
              format: {"Mydate":"date should be in correct format"},
              required: {
                "Mydate": 'Date is missing'},
            }} 
```

**Sample data**

```javascript
var data = {
      "expediteOrder": false,
      "dateNeeded": "",
    }
```

ERROR:
keyword schema is invalid: data/format should be string
    at Object.useCustomRule (C:\workspace\POTS-API\node_modules\ajv\lib\compile\index.js:264:20)
    at Object.generate_custom [as code] (C:\workspace\POTS-API\node_modules\ajv\lib\dotjs\custom.js:32:24)
    at generate_validate (C:\workspace\POTS-API\node_modules\ajv\lib\dotjs\validate.js:353:35)
    at localCompile (C:\workspace\POTS-API\node_modules\ajv\lib\compile\index.js:88:22)
    at Ajv.compile (C:\workspace\POTS-API\node_modules\ajv\lib\compile\index.js:55:13)
    at Ajv._compile (C:\workspace\POTS-API\node_modules\ajv\lib\ajv.js:346:27)
    at Ajv.compile (C:\workspace\POTS-API\node_modules\ajv\lib\ajv.js:112:37)
    at Object.<anonymous> (C:\workspace\POTS-API\test\unit\data-validation\tp.ts:64:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)

Expect:
It should show my custom error message.

Please help!

**Comment by MeenalYengul** [comment]
I have solved it by doing like this in schema :
"date": {"type": "string","format": "date-time", errorMessage:{type:'Date must be a "mm-dd-yy" format........', format:'Check Date format'}},


but now I want to write error message for array of number for checking its data type. I want custom message

**Comment by epoberezkin** [comment]
This issue is related to errorMessage keyword that is in ajv-errors package, so it should be submitted there.
Based on the error message it looks that you are not using it as documented, please review the docs in ajv-errors and if it does not help:
1. if you believe errorMessage does not behave as documented - please submit bug report with the full code sample
2. If you propose a change - please submit change proposal (including the code sample of the proposed change being used)
3. You need help using the package - please submit the question to StackOverflow

**Comment by rofrol** [comment]
Example repo https://github.com/rofrol/ajv-regexp-errormessage-example
