### ISSUE TITLE
Error: custom keyword definition is invalid: data.errors should be boolean

### ISSUE THREAD

**Issue by yooouuri** [ajv-validator/ajv#942]
vue.js uses this library and I can't run yarn serve because of the following error:

```
$ yarn serve
yarn run v1.13.0
$ vue-cli-service serve
 INFO  Starting development server...
 ERROR  Error: custom keyword definition is invalid: data.errors should be boolean
Error: custom keyword definition is invalid: data.errors should be boolean
    at Ajv.addKeyword (/Users/youri/code/project/node_modules/ajv/lib/keyword.js:65:13)
    at module.exports (/Users/youri/code/project/node_modules/ajv-errors/index.js:10:7)
    at Object.<anonymous> (/Users/youri/code/project/node_modules/schema-utils/src/validateOptions.js:22:1)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tetreault** [comment]
This also breaks simply running `npm run dev` in nuxt. Second time in a week new nuxt projects have been broken, last sunday it was a bad PR on terser that broke `npm run generate` :(

**Comment by ghost** [comment]
I can confirm the same issue.

file-loader@3.0.1 stopped working because it has ajv as dependency.

**Comment by caldempsey** [comment]
I've opened an earlier ticket, but yeah this is a pretty big deal :package:

**Comment by yooouuri** [comment]
@mmacheerpuppy ill close mine 👍

**Comment by tetreault** [comment]
I commented in the main issue #941 but for nuxt doing `npm i -d ajv@5.0.0` resolved this issue for me.

**Comment by aaaguirrep** [comment]
I have created a new project in nuxtjs for spa and when i run "yarn run dev" it shows: ERROR  custom keyword definition is invalid: data/errors should be boolean

**Comment by tetreault** [comment]
@aaaguirrep see my comment right above yours. Im using nuxt as well and my comment worked for me. Note, you dont need to use 5.0.0 but can use 6.8.1.

**Comment by aaaguirrep** [comment]
Hi, i have checked the issue #941 and i have fixed it.
